const propertiesData = [
  {
    id: 1,
    image: "estate2",
    title: "Italian villa",
    desc: "The villa is located on the beach facing the mainland",
    category: "Party villa",
    sqmeters: 150,
    beds: 2,
    country: "Italy",
    type: "Party Villa",
    price: 100000,
  },
  {
    id: 2,
    image: "estate3",
    title: "Italian villa",
    desc: "The villa is located on the beach facing the mainland",
    category: "Party villa",
    sqmeters: 150,
    beds: 2,
    country: "Norway",
    type: "Party Villa",
    price: 110000,
  },
  {
    id: 3,
    image: "estate4",
    title: "Italian villa",
    desc: "The villa is located on the beach facing the mainland",
    category: "Party villa",
    sqmeters: 150,
    beds: 2,
    country: "Bulgaria",
    type: "Party Villa",
    price: 135000,
  },
  {
    id: 4,
    image: "estate4",
    title: "Italian villa",
    desc: "The villa is located on the beach facing the mainland",
    category: "Party villa",
    sqmeters: 150,
    beds: 2,
    country: "India",
    type: "Party Villa",
    price: 160000,
  },
];

export { propertiesData };
